#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  led1,           sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Lift1R,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port9,           Lift1L,        tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//3495f
//#include "tasks.h"

int count = 0;
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
string bat1, bat2;

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	while(nLCDButtons != centerButton)
	{

		switch(count)
		{
		case 0:

			displayLCDCenteredString(0, "Left Auton");
			displayLCDCenteredString(1, "<   Enter   >");
			waitForPress();

			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if (nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 1;
			}
			break;


		case 1:

			displayLCDCenteredString(0, "Right Auton");
			displayLCDCenteredString(1, "<   Enter   >");

			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if (nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 2:

			displayLCDCenteredString(0, "Skills Auton");
			displayLCDCenteredString(1, "<   Enter   >");

			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if (nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 3:

			displayLCDString(0, 0, "Primary: ");
			sprintf(bat1, "%1.2f%c", nImmediateBatteryLevel/1000.0, 'v');
			displayNextLCDString(bat1);

			displayLCDString(1, 0, "Backup: ");
			sprintf(bat2, "%1.2f%c", BackupBatteryLevel/1000.0, 'v');
			displayNextLCDString(bat2);

			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if (nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;

			if(nLCDButtons == centerButton)
			{return;}

		}


	}
}



task autonomous()
{

	switch(count)
	{
	case 0:
		resetMotorEncoder(lift3);
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);

		motor[lift1] = motor[lift2] = -20;

		//to cube
		move(24, 1);

		//pick up cube
		claw(1500, 1);
		motor[claw1] = motor[claw2] = 20;
		while(nMotorEncoder[lift3] < 100)
		{
			motor[lift1] = motor[lift2] = 127;
			motor[lift3] =  -127;
		}
		motor[lift1] = motor[lift2] = -10;
		motor[lift3] =  10;

		//turn
		while(nMotorEncoder(rightMotor) > -575*3/4)
		{
			motor[rightMotor] = -127;
		}
		motor[leftMotor] = motor[rightMotor] = 0;

		//to fence then lift
		move(-15, -1);
		while(nMotorEncoder[lift3] < 750)//540
		{
			motor[lift1] = motor[lift2] = 127;
			motor[lift3] =  -127;
		}
		motor[lift1] = motor[lift2] = -10;
		motor[lift3] =  -10;

		//throw cube
		claw(500, -1);
		motor[lift1] = motor[lift2] = 0;
		wait1Msec(500);

		//fence hieght and turn
		while(nMotorEncoder[lift3] > 550)//540
		{
			motor[lift1] = motor[lift2] = -127;
			motor[lift3] =  127;
		}
		motor[lift1] = motor[lift2] = -10;
		motor[lift3] =  -10;

		resetMotorEncoder(leftMotor);
		while(nMotorEncoder(leftMotor) < 1500*3/4)
		{
			motor[leftMotor] = 127;
		}
		motor[leftMotor] = 0;

		//clear fence
		claw(150, -0.5);

		move(10, 1);

		break;

	case 1:
		resetMotorEncoder(lift3);
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);

		motor[lift1] = motor[lift2] = -20;

		move(24, 1);

		claw(1500, 1);
		motor[claw1] = motor[claw2] = 30;
		while(nMotorEncoder[lift3] < 100)//540
		{
			motor[lift1] = motor[lift2] = 127;
			motor[lift3] =  -127;
		}
		motor[lift1] = motor[lift2] = -10;
		motor[lift3] =  -10;

		while(nMotorEncoder(leftMotor) > -575*3/4)
		{
			motor[leftMotor] = -127;
		}
		motor[leftMotor] = motor[rightMotor] = 0;

		move(-12, -1);

		while(nMotorEncoder[lift3] < 750)//540
		{
			motor[lift1] = motor[lift2] = 127;
			motor[lift3] =  -127;
		}
		motor[lift1] = motor[lift2] = -10;
		motor[lift3] =  -10;

		claw(500, -1);
		motor[lift1] = motor[lift2] = 0;
		wait1Msec(500);

		while(nMotorEncoder[lift3] < 550)//540
		{
			motor[lift1] = motor[lift2] = 127;
			motor[lift3] =  -127;
		}
		motor[lift1] = motor[lift2] = -10;
		motor[lift3] =  -10;

		resetMotorEncoder(rightMotor);
		while(nMotorEncoder(rightMotor) < 1500*3/4)
		{
			motor[rightMotor] = 127;
		}
		motor[rightMotor] = 0;

		claw(150, -0.5);

		move(10, 1);
		break;

	case 2:

		wait1Msec(100);
		move(20, -1);

		claw(2000, 1);

		lift(45);

		move(20, -1);

		motor[leftMotor] = motor[rightMotor] = -127;
		lift(80);


		break;
	default:

		resetMotorEncoder(lift3);
		while(nMotorEncoder[lift3] < 540)//540
		{
			motor[lift1] = motor[lift2] = 127;
			motor[lift3] =  -127;
		}
		motor[lift1] = motor[lift2] = -10;
		motor[lift3] =  -10;
		claw(750, 1);

		move(40, 1);

		claw(500, 1);

		move(-10, -1);
		break;
	}

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	resetMotorEncoder(lift1);
	while (true)
	{
		int leftstick = vexRT[Ch3];
		int rightstick = vexRT[Ch2];
		int liftbuttonU = vexRT[Btn6U];
		int liftbuttonD = vexRT[Btn6D];
		int clawopen = vexRT[Btn5U];
		int clawclose = vexRT[Btn5D];
		int Sound = vexRT[Btn7D];
		string bat1, bat2;

		if(Sound == 1)
		{
			playSoundFile("1.wav");
		}


		//left motor control
		if (leftstick > 10 || leftstick < -10){
			motor [leftMotor] = leftstick;
			//			motor [leftMotorB] = leftstick;
		}
		else
			motor [leftMotor] = 0;
		//			motor [leftMotorB] = 0;

		//right motor control
		if (rightstick > 10 || rightstick <-10){
			motor [rightMotor] = rightstick;
			//			motor [rightMotorB] = rightstick;
		}
		else
			motor [rightMotor] = 0;
		//			motor [rightMotorB] = 0;

		//Lift control
		if (liftbuttonU == 1)
		{
			motor [lift1] = motor [lift2] =  127;
			motor [lift3] = -127;
		}
		else if (liftbuttonD == 1)
		{
			motor [lift1] = motor [lift2] = -127;
			motor[lift3] =  127;
			}	else 	{
			motor [lift1] = -10;
			motor [lift2] = -10;
			motor [lift3] = -10;
		}


		//Claw control
		if (clawopen == 1){
			motor [claw1] = 127;
			motor [claw2] = 127;
		}
		else if (clawclose == 1){
			motor [claw1] = -127;
			motor [claw2] = -127;
		}
		else
		{
			motor [claw1] = 10;
			motor [claw2] = -10;
		}

		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDString(0, 0, "Primary: ");
		sprintf(bat1, "%1.2f%c", nImmediateBatteryLevel/1000.0, 'v');
		displayNextLCDString(bat1);

		displayLCDString(1, 0, "Backup: ");
		sprintf(bat2, "%1.2f%c", BackupBatteryLevel/1000.0, 'v');
		displayNextLCDString(bat2);

	}

}
