#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw1,         tmotorVex393_HBridge, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port4,           hang,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           lift1,         tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port7,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task main()
{

for(int x =0; x< 3; x++) {
		resetMotorEncoder(lift1);
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);

		while(nMotorEncoder[rightMotor] < 2400)//forward to fence
		{
			motor[rightMotor] = motor[leftMotor] = 110;
		}
		motor[rightMotor] = motor[leftMotor] = 0;
		wait1Msec(100);

		resetMotorEncoder(rightMotor);
		while(getMotorEncoder(lift1) < 1200)//lift up almost to top
		{
			motor[lift1] = motor[lift2] = 127;

		}

		motor[lift1] = motor[lift2] = 127;
		motor[claw1] = motor[claw2] = -127;
		wait1Msec(750);//finishes lift raise, and lets go of cube

		motor[lift1] = motor[lift2] = 0;
		motor[claw1] = motor[claw2] = 0;
		motor[rightMotor] = motor[leftMotor] = 0;
		wait1Msec(500);
	}

}
