#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           claw1,         tmotorVex393_HBridge, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port4,           hang,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           lift1,         tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port7,           lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          claw2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

void move(int dist)
{
	//while(
}

task autonomous()
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);
while(nMotorEncoder[leftMotor] > -1200)
	{
		motor[rightMotor] = motor[leftMotor] = -127;
	}
		motor[rightMotor] = motor[leftMotor] = -127;

for(int x =0; x< 4; x++) {
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

		motor[claw1] = motor[claw2] = 120;			//close claw on objects
		wait1Msec(1500);
		motor[claw1] = motor[claw2] = 50;

	resetMotorEncoder(rightMotor);
while(nMotorEncoder[rightMotor] > -2400)	//backwards to fence
	{
		motor[rightMotor] = motor[leftMotor] = -127;
	}
		motor[rightMotor] = motor[leftMotor] = 0;
		wait1Msec(10);

while(getMotorEncoder(lift1) < 1000)			//lift up almost to top
	{
		motor[lift1] = motor[lift2] = 127;
	}
		wait1Msec(1000);

		motor[lift1] = motor[lift2] = 127;
		motor[claw1] = motor[claw2] = -127;
		wait1Msec(200);												//finishes lift raise, and lets go of cube

		motor[claw1] = motor[claw2] = 0;

while(nMotorEncoder(lift1) > 10)					//lowers lift
	{
		motor[lift1] = motor[lift2] = -127;
	}
		motor[lift1] = motor[lift2] = -127;
		wait1Msec(10);

		motor[claw1] = motor[claw2] = -127;			// opens claw
		wait1Msec(2000);
		motor[claw1] = motor[claw2] = 0;

	resetMotorEncoder(rightMotor);
while(nMotorEncoder(rightMotor) < 2400)			//return to loop starting position
		{
			motor[rightMotor] = motor[leftMotor] = 127;
		}
		motor[rightMotor] = motor[leftMotor] = 0;
		wait1Msec(10);
	}



	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

while(nMotorEncoder[rightMotor] > -2400)
		{
			motor[rightMotor] = motor[leftMotor] = -127;
		}
			motor[rightMotor] = motor[leftMotor] = 0;
		resetMotorEncoder(rightMotor);

while(nMotorEncoder[rightMotor] < 1375)
		{
			motor[rightMotor] = 127;
		}
	resetMotorEncoder(rightMotor);
while(nMotorEncoder[rightMotor] < 1200)
		{
			motor[rightMotor] = motor[leftMotor] = 127;
		}
			motor[rightMotor] = motor[leftMotor] = 0;

			motor[claw1] = motor[claw2] = 110;
			wait1Msec(2000);//close claw on cube

			motor[lift1] = motor[lift2] = 80;
			wait1Msec(500);
			motor[lift1] = motor[lift2] = 20;


		resetMotorEncoder(rightMotor);
while(nMotorEncoder[rightMotor] > -1375)//turns around, clockwise, back to fence
		{
			motor[rightMotor] = -127;
		}
			motor[rightMotor] = 0;
			wait1Msec(100);

		resetMotorEncoder(rightMotor);
while(nMotorEncoder[rightMotor] > -1254)//backs up to fence
{
			motor[rightMotor] = motor[leftMotor] = -110;
}
			motor[rightMotor] = motor[leftMotor] = 0;
			wait1Msec(100);

while(getMotorEncoder(lift1) < 1200)//lift up almost to top
	{
			motor[lift1] = motor[lift2] = 127;
	}
			motor[lift1] = motor[lift2] = 15;
			wait1Msec(10);

			motor[lift1] = motor[lift2] = 127;
			motor[claw1] = motor[claw2] = -127;
			wait1Msec(750);//finishes lift raise, and lets go of cube

			motor[lift1] = motor[lift2] = 0;
			motor[claw1] = motor[claw2] = 0;
			motor[rightMotor] = motor[leftMotor] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		int leftstick = vexRT[Ch3];
		int rightstick = vexRT[Ch2];
		int liftbuttonU = vexRT[Btn6U];
		int liftbuttonD = vexRT[Btn6D];
		int clawopen = vexRT[Btn5U];
		int clawclose = vexRT[Btn5D];
		int hango = vexRT[Btn8U];
		int hangi = vexRT[Btn8D];


		//left motor control
		if (leftstick > 10 || leftstick < -10){
			motor [leftMotor] = leftstick;
			//			motor [leftMotorB] = leftstick;
		}
		else
			motor [leftMotor] = 0;
		//			motor [leftMotorB] = 0;

		//right motor control
		if (rightstick > 10 || rightstick <-10){
			motor [rightMotor] = rightstick;
			//			motor [rightMotorB] = rightstick;
		}
		else
			motor [rightMotor] = 0;
		//			motor [rightMotorB] = 0;

		//Lift control
		if (liftbuttonU == 1){
			motor [lift1] = 127;
			motor[lift2] = 127;
		}
		else if (liftbuttonD == 1){
			motor [lift1] = -127;
			motor[lift2] = -127;
		}
		else {
			motor [lift1] = 0;
			motor[lift2] = 0;
		}
		//Claw control
		if (clawopen == 1){
			motor [claw1] = 127;
			motor [claw2] = 127;
		}
		else if (clawclose == 1){
			motor [claw1] = -127;
			motor [claw2] = -127;
		}
		else
		{
			motor[claw1] = 10;
			motor[claw2] = -10;
		}

		//linear slide control
		if (hango == 1)
		{
			motor [hang] = 127;
		}
		else if (hangi == 1)
		{
			motor [hang] = -127;
		}
		else
		{
			motor[hang] = 0;
		}
	}

}
